### ISSUE TITLE
/usr/bin/env: node --harmony: No such file or directory on running jiran config in Ubuntu

### ISSUE THREAD

**Issue by vishnub1626** [danielkmariam/jiran#9]
`jiran config` in Ubuntu gives `/usr/bin/env: node --harmony: No such file or directory` error.

**Comment by danielkmariam** [comment]
hello @vishnu-b thanks for trying `jiran` and raising the issue

I think you have installed node using `sudo apt-get install nodejs` if so can you add a symlink so you can use is as `/usr/bin/node`?

`sudo apt-get install nodejs`
`sudo apt-get install npm`

`sudo ln -s /usr/bin/nodejs /usr/bin/node`

Let me know if this resolves your issue.

Thanks

**Comment by danielkmariam** [comment]
@vishnu-b I hope my previous comment resolved your issue.

Closing this as resolved
